FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard/ ./dashboard/
COPY DATA/ ./DATA/
COPY models/ ./models/

EXPOSE 8050

CMD ["python", "dashboard/app.py"]