services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mercalia-api
    ports:
      - "8000:8000"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: mercalia-dashboard
    ports:
      - "8050:8050"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api